# sitemap settings

template: sitemap.twig
xml_template: sitemap_xml.twig

ignore:
  - /page/home
  - /404-not-found
  - /old-browser

## ignore by "slug" of contenttype
# ignore_contenttype:
#  - pages

## ignore listing templates
ignore_listing: false

## when ignore_listing is not = true: listings templates may not exist yet may contain child pages.
## add path will keep listing visible in tree but remove its link.
remove_link:
 - /pages
