main:
    -
        path: homepage
        title: 'Retourner à la page d''accueil'
        label: Accueil
    -
        path: a-propos
        label: 'À propos'
    -
        path: services
        label: Services
    -
        path: references
        label: Références
    -
        class: ' scroll-to'
        link: '/#contact'
        label: Contact
