# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Accueil
      title: Retourner à la page d'accueil
      path: homepage
    - label: Pages
      link: '#'
      submenu:
        - label: Toutes
          path: pages/
        - label: À propos
          path: page/about
        - label: Contact
          path: page/contact
    - label: Pages d'erreurs
      link: '#'
      submenu:
          - label: Navigateur obsolète
            path: page/old-browser
          - label: Erreur 404
            path: page/404-not-found
