# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Accueil
      title: Retourner à la page d'accueil
      path: homepage
    - label: À propos
      path: a-propos
    - label: Services
      path: services
    - label: Références
      path: references
    - label: Contact
      link: /#contact
      class: " scroll-to"
    # - label: Pages d'erreurs
    #   link: '#'
    #   submenu:
    #       - label: Navigateur obsolète
    #         path: page/old-browser
    #       - label: Erreur 404
    #         path: page/404-not-found
